version: '2'

services:
  angular:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client:/app    
  
  express:
    build: express-server
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - ./express-server:/usr/src/app
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"